services:
  - type: web
    name: qhse-manager-pro
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: CLOUD_MODE
        value: true
      - key: SECRET_KEY
        generateValue: true
